import BlackImage from '@/assets/images/Perfumes/Black.jpeg'
import BlueImage from '@/assets/images/Perfumes/Blue.jpeg'
import BlueTwoImage from '@/assets/images/Perfumes/Blue-2.jpeg'
import GreenImage from '@/assets/images/Perfumes/Green.jpeg'
import GreenTwoImage from '@/assets/images/Perfumes/Green-2.jpeg'
import GreenThreeImage from '@/assets/images/Perfumes/Green-3.jpeg'
import OrangeImage from '@/assets/images/Perfumes/Orange.jpeg'
import PurpleImage from '@/assets/images/Perfumes/Purple.jpeg'
import PurpleTwoImage from '@/assets/images/Perfumes/Purple-2.jpeg'
import RoseImage from '@/assets/images/Perfumes/Rose.jpeg'
import SandleImage from '@/assets/images/Perfumes/Sandle.jpeg'
import ViloteImage from '@/assets/images/Perfumes/vilote.jpeg'

export { BlackImage }
export { BlueImage }
export { BlueTwoImage }
export { GreenImage }
export { GreenTwoImage }
export { GreenThreeImage }
export { OrangeImage }
export { PurpleImage }
export { PurpleTwoImage }
export { RoseImage }
export { SandleImage }
export { ViloteImage }
